backend/lib/backend_web/router.ex
defmodule BackendWeb.Router do
  use BackendWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BackendWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BackendWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/leaderboard", PageController, :leaderboard

    # Activities
    get "/activity/:activity", ActivityController, :set

    # Shopping
    get "/shop/:product", ShopController, :buy

    # Donations
    post "/donate", DonationController, :donate

    # Attacks
    post "/attack", AttackController, :attack

    # Session management
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/registrations", UserController, only: [:create, :new]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BackendWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BackendWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

backend/lib/backend_web/templates/page/about.html.heex
<p>
  Created by Trent Small and Kenny Broyles for the 2022 Global Game Jam.
</p>

backend/lib/backend_web/templates/page/index.html.heex
<% user = current_user(@conn) %>
<div class="flex flex-row justify-around flex-wrap">
  <div class="p-4 border rounded border-gray-500">
    <div class="text-lg cursor-help"
         title="The items that are currently in your posession.">
      Inventory
    </div>
    <%= case user.team do %>
      <% "purple" ->  %>
        <div class="text-purple-200">
          Team: <%= user.team %>
        </div>
      <% "green" -> %>
        <div class="text-green-200">
          Team: <%= user.team %>
        </div>
    <% end %>
    <div class="text-yellow-200">
      Victory points: <%= Backend.Game.victory_points_for_user(user) %>
    </div>
    <% items = user.inventory.items %>
    <%= if items == %{} do %>
      Nothing.
    <% else %>
      <ul>
        <%= for {item_name, amount} <- items do %>
          <% item = Backend.Items.get_item(String.to_atom(item_name)) %>
          <% damage_str = if Map.has_key?(item, :weapon) do
               " (#{item.weapon.damage} damage)" 
             else 
               ""
             end
          %>
          <li><%= "#{item.label}: #{amount}#{damage_str}" %></li>
        <% end %>
      </ul>
    <% end %>
    <%= button "Refresh", to: Routes.page_path(@conn, :index), method: :get %>
  </div>

  <div class="p-4 border rounded border-gray-500">
    <div class="text-lg cursor-help"
         title="You can choose to perform a single activity passively.">
      Activities
    </div>
    <div class="card-body">
      Current activity: <%= user.passive_activity %>
      <h2>Choose a new activity</h2>
      <ul>
        <%= for {_, %{generated: item}} <- Backend.Items.generated_items() do %>
          <li>
            <%= button(
                "#{item.activity_label} (every #{item.seconds_per_item}s)",
                to: Routes.activity_path(@conn, :set, item.activity),
                method: :get
              )
            %>
          </li>
        <% end %>
        <li>
          <%= button "Defend", 
            to: Routes.activity_path(@conn, :set, "defend"),
            title: "When defending, any attacks you receive deal half damage.",
            method: :get
          %>
        </li>
      </ul>
    </div>
  </div>

  <div class="p-4 border rounded border-gray-500">
    <div class="text-lg cursor-help"
         title="You can spend resources to buy other resources. 'Required' resources are not consumed.">
      Shop
    </div>
    <div class="card-body">
      <ul>
        <%= for {key, item} <- Backend.Items.for_sale_items() do %>
          <li>
            <%= button Backend.Items.for_sale_cost_string(item), 
              to: Routes.shop_path(@conn, :buy, Atom.to_string(key)),
              method: :get
            %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="p-4 border rounded border-gray-500">
    <div class="text-lg cursor-help"
         title="You may donate any number of resources to any other player.">
      Donations
    </div>
    <div class="card-body">
      <%= form_for @conn, Routes.donation_path(@conn, :donate), 
           [class: "flex flex-col", as: :donation], fn f -> %>
        <%= text_input f, 
          :target, 
          placeholder: "Username to donate to" 
        %>
        <%= number_input f, :amount, value: 1 %>
        <%= select f, 
          :product, 
          value: Backend.Game.all_item_atoms_for_user(user) 
            |> Enum.map(fn atom -> 
              [key: Backend.Items.get_item(atom).label, value: atom]
            end)
        %>
        <div class="p-2">
          <%= submit "Donate" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="p-4 border rounded border-gray-500">
    <div class="text-lg cursor-help"
         title="You may attack any player's resources with weapons.">
      Attacks
    </div>
    <div class="card-body">
      <%= form_for @conn, Routes.attack_path(@conn, :attack), 
          [class: "flex flex-col", as: :attack], fn f -> %>
        <%= label f, :target %>
        <%= text_input f, 
          :target, 
          placeholder: "Username to attack" 
        %>
        <%= select f, 
          :target_product, 
          value: Backend.Items.get_items()
            |> Enum.map(fn {atom, item} -> [key: item.label, value: atom]
          end )
        %>
        <%= label :amount, "Attack with" %>
        <%= number_input f, :amount, value: 1 %>
        <%= select f, 
          :product, 
          value: Backend.Game.all_weapon_atoms_for_user(user) 
            |> Enum.map(fn atom -> 
              item = Backend.Items.get_item(atom)
              [key: item.label, value: atom] 
            end)
        %>
        <div class="p-2">
          <%= submit "Attack" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="p-4 mt-10 w-full bg-gray-900 rounded">
  <div class="text-lg">
    Logs
  </div>
  <pre class="whitespace-pre-wrap">
    <%= for log <- @conn.assigns.logs do %><%= elem(log, 0) %>: <%= elem(log, 1) %>
    <% end %>
  </pre>
</div>

backend/lib/backend_web/templates/page/leaderboard.html.heex
<div class="p-4 border rounded border-gray-500">
  <div class="text-lg">
    Top players
  </div>
  <table class="bg-gray-900 w-64">
    <tr>
      <th>Username</th>
      <th>Victory points</th>
    </tr>
    <%= for user <- @conn.assigns.users do %>
      <tr>
        <td><%= user.username %></td>
        <td><%= Backend.Game.victory_points_for_user(user) %></td>
      </tr>
    <% end %>
  </table>
</div>