backend/lib/backend_web/router.ex
defmodule BackendWeb.Router do
  use BackendWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BackendWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BackendWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/leaderboard", PageController, :leaderboard

    # Activities
    get "/activity/:activity", ActivityController, :set

    # Shopping
    get "/shop/:product", ShopController, :buy

    # Donations
    post "/donate", DonationController, :donate

    # Attacks
    post "/attack", AttackController, :attack

    # Session management
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/registrations", UserController, only: [:create, :new]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BackendWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BackendWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

backend/lib/backend_web/views/layout_view.ex
defmodule BackendWeb.LayoutView do
  use BackendWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

backend/lib/backend_web/templates/layout/app.html.heex
<main class="pt-32 sm:px-4 lg:px-32 text-white">
  <div class="flex flex-row justify-center">
    <%= if get_flash(@conn, :info) do %>
      <div class="p-2 mb-2 rounded bg-gray-900 text-white">
        <%= get_flash(@conn, :info) %>
      </div>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <div class="p-2 mb-2 rounded bg-red-900 text-white">
        <%= get_flash(@conn, :error) %>
      </div>
    <% end %>
  </div>
  <%= @inner_content %>
</main>

backend/lib/backend_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

backend/lib/backend_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "World War IV", suffix: " - GGJ2022" %>
    <link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Supermercado+One&family=Titillium+Web&display=swap" rel="stylesheet">
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="m0 h-screen w-full bg-black text-white">
    <header class="fixed w-full px-10 py-2 glow-shadow bg-purple-800 text-white flex justify-between items-center">
      <div class="text-display text-2xl">
        <%= link "World War IV", to: Routes.page_path(@conn, :index) %>
      </div>
      <nav class="flex flex-row justify-center items-center">
          <%= if signed_in?(@conn) do %>
            <span class="p-1">
              Logged in as <%= current_username(@conn) %>
            </span>
            <span class="p-1">
              <%= button "Log out", to: Routes.session_path(@conn, :delete), method: :delete %>
            </span>
          <% else %>
            <span class="p-1"><%= button "Log in", to: Routes.session_path(@conn, :new), method: :get %></span>
            <span class="p-1"><%= button "Sign up", to: Routes.user_path(@conn, :new), method: :get%></span>
          <% end %>
          <span class="p-1">
            <%= button "Leaderboard", to: Routes.page_path(@conn, :leaderboard), method: :get %>
          </span>
          <span class="p-1">
            <%= button "About", to: Routes.page_path(@conn, :about), method: :get %>
          </span>
      </nav>
    </header>
    <%= @inner_content %>
  </body>
</html>